version: '3.1'
services:
  db:
    image: postgres:14
    user: postgres
    container_name: postgres14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  odoo:
    image: joshkarp/taskflow-odoo:12
    container_name: odoo12
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: odoo -i web_flow,l10n_us_bank,crm,api_ocrolus,credit_report_us,api_ocrolus_crm,api_plaid_ocrolus,api_datamerch,config_backd -d localhost
